#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERSEPROXY_YNH
#=================================================

# Validate reverse proxy destination
rp_validate_proxy_path

# Validate assets_path
rp_validate_assets_path

# Special case for "/" path
rp_handle_webroot

# Configure nginx
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

ynh_config_add --jinja --template = "nginx.conf" --destination="/etc/nginx.conf.d/${domain}.d/${app}.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
