#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERSEPROXY_YNH
#=================================================

# Validate reverse proxy destination
rp_validate_proxy_path

# Validate assets_path
rp_validate_assets_path

# Special case for "/" path
rp_handle_webroot

# Configure nginx
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
