#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERSEPROXY_YNH
#=================================================

# Remove configuration files
ynh_safe_rm /etc/nginx/conf.d/$domain.d/$app.conf

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
