#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERSEPROXY_YNH
#=================================================

# Remove configuration files
ynh_secure_remove "/etc/nginx/conf.d/${domain}.d/${app}.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
