#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERSEPROXY_YNH
#=================================================

# Validate proxy destination
rp_validate_proxy_path

# Validate assets_path
rp_validate_assets_path

# Special case for "/" path
rp_handle_webroot

# Configure nginx
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
